# Generated by Django 4.1.1 on 2022-09-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deepthought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepthought',
            name='pub_date',
        ),
    ]
